version: '3.0'

x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:
  rox:
    image: "${APP_IMAGE}"
    ports:
      - 3000:3000
      - 3001:3001
      - 9090:9090
    environment:
      - DEFAULT_LANGUAGE_CODE
      - OTL_EXPORTER_ZIPKIN_URL
      - OTL_EXPORTER_JAEGER_URL
      - OTL_EXPORTER_PROMETHEUS_PORT
      - OTL_EXPORTER_GCP_ENABLED
      - EVENTS_SERVER_ENABLED
      - LOGS_LEVEL
    deploy:
      resources:
        limits:
          memory: 500M

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
    - "8081:8081"
    volumes: 
      - ./uffizzi/nginx:/etc/nginx
      - ./uffizzi/nginx/html:/usr/share/nginx/html